# Upload the game source files directly to itch.io - we're only using plain ole' html/css/js right now
name: UploadToitch
run-name: Butler Testing

env:
  PROJ_DIR: src
  BUTLER_LINK: https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
  ITCH_GAME_NAME: gdacdavis/gdac-yearbook
  
on: 
  push:
    branches: 
      - main
    paths:
      - 'src/**'
  workflow_dispatch:

jobs:
  TestButler:
    runs-on: ubuntu-latest

    steps:
      - name: Debug
        run: |
          pwd
          tree -L 4
      
      # Zip before uploading to itch isn't required, but lower upload size
      - name: Zip Source
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r ${{env.PROJ_DIR}}.zip ../${{env.PROJ_DIR}}
          
      - name: Download Butler
        run: |
          curl -L -o butler.zip ${{env.BUTLER_LINK}}
          unzip butler.zip
          chmod +x butler
          ./butler -V
          tree -L 4
          
      - name: Push Build to Butler
        run: |
          ./butler push ${{env.PROJ_DIR}}.zip ${{env.ITCH_GAME_NAME}}:web
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
